### ISSUE TITLE
Store complete nodes and gateway connection data in flash ? 

### ISSUE THREAD

**Issue by quangvankts** [gmag11/EnigmaIOT#11]
Hi gmag11
Thanks for the great library with very detailed documentation. I have few questions: 
- How do I hardcode network name and network key for both nodes and gateway so I don't have to configure them individually after flashing?
- How do I save complete nodes and gateway current data into flash (including shared key, valid status etc) so they can load it up, skip registration and exchange data straightaway after a cold boot (I know it only takes 200ms to register but I want to experiment how fast nodes can work)
- DEBUG seems only work on my ESP8266 node but not ESP32 gateway. I tried "#define DEBUG_LEVEL VERBOSE" and "#define DEBUG_ESP_PORT Serial" at the main sketch with no effect. Serial.printf() still works as normal. (Im using Platform IO latest core)  
Thanks

**Comment by gmag11** [comment]
Hello, These are three questions. I'll separate them into multiple issues and will close this. You can check #12, #13 and #14
