### ISSUE TITLE
DEBUG setting in EnigmaIOTConfig.h has no effect on ESP32 platform

### ISSUE THREAD

**Issue by gmag11** [gmag11/EnigmaIOT#14]
@quangvankts asked in #11

DEBUG seems only work on my ESP8266 node but not ESP32 gateway. I tried "#define DEBUG_LEVEL VERBOSE" and "#define DEBUG_ESP_PORT Serial" at the main sketch with no effect. Serial.printf() still works as normal. (Im using Platform IO latest core)

**Comment by gmag11** [comment]
That's right, ESP32 platform uses different mechanism to configure debug level.

If you use Arduino you need to configure debug level in board configuration (`core debug level`).

If you use Platformio you may read this section in Platformio docs: https://docs.platformio.org/en/latest/platforms/espressif32.html#debug-level

**Comment by quangvankts** [comment]
Yes I understand how debug configuration work on EPS32 now 
Thanks !
