### ISSUE TITLE
API doesn't send correct json

### ISSUE THREAD

**Issue by G2G2G2G** [gmag11/EnigmaIOT#20]
All of the web API sends single quotes instead of double quotes

https://github.com/gmag11/EnigmaIOT/blob/master/docs/api.md

**Comment by gmag11** [comment]
Yes, this is intended to simplify string management in C++ code. single quotes are valid in JSON, aren't they? At least Insomnia shows correct decoded JSON data.

**Comment by G2G2G2G** [comment]
Yes I saw that in your code, unfortunately no JSON spec is double quotes only, some references here: https://stackoverflow.com/questions/14355655/jquery-parsejson-single-quote-vs-double-quote

I can edit it, if you don't have time, but I would just switch all of the `'` to `\"` instead

**Comment by gmag11** [comment]
Thank you. I'll change this in next release.

**Comment by gmag11** [comment]
It should be solved in a5b2a76. Thanks again
