### ISSUE TITLE
Wrong use of searchForGateway (&rtcmem_data) ?

### ISSUE THREAD

**Issue by arihantdaga** [gmag11/EnigmaIOT#27]
Hi @gmag11 , I came across these if conditions
`if (searchForGateway (&rtcmem_data), true)` in lines 
https://github.com/gmag11/EnigmaIOT/blob/db1feacc9287ae786eba8caf87142d031d123706/src/EnigmaIOTNode.cpp#L752
https://github.com/gmag11/EnigmaIOT/blob/db1feacc9287ae786eba8caf87142d031d123706/src/EnigmaIOTNode.cpp#L761

was it meant to be - `if (searchForGateway (&rtcmem_data, true))`
I noticed this problem because by node was always trying to conenct to the gateway even when it could not find the gateway. 
It would print this in the logs. 
```
 Gateway SMART_S not found
Found gateway. Storing
```

**Comment by gmag11** [comment]
I guess you are right. Would you mind to do a pull request over dev branch? Thank you!

**Comment by arihantdaga** [comment]
Sure, yeah.

**Comment by gmag11** [comment]
Merged. Will be published in next release
