### ISSUE TITLE
More permissive license?

### ISSUE THREAD

**Issue by ulno** [gmag11/EnigmaIOT#3]
This looks like a really cool project and there are lots of things in here, I still want to implement.
I am the main author of IoTempower (https://github.com/iotempire/iotempower), my vision would be to merge or integrate EnigmaIOT, PJON (https://github.com/gioblu/PJON),  and IoTempower, maybe offer some more (static) mesh-functionality, but PJON should allow that easily.

However, I can not do that out of legal reasons as you picked the GPLv3 as a license. If I use code from you, I have to put all my code under the GPLv3 and also all projects created with it. That makes it very unattractive to use IoTempower (and also EnigmaIOT) in a commercial or even university setting.

I can understand that you want changes and fixes to your code back in the project, but could you at least relax the license to the LGPLv3? That would allow us to use the code at least as a library in other projects without adopting the license itself. If you just seek attribution and could trust (most of us) other developers to contribute changes back and help fix problems, of course an even more permissive license like MIT or BSD would probably be appreciated by the developer community.

**Comment by gmag11** [comment]
Thank you for your suggestion. In this stage I prefer keep license as it is. Project is not mature enough. It is not stable enough to be used in commercial / industrial products. Besides I'd like that derived projects are open and free software too.
