### ISSUE TITLE
Missing library "arduino.h"

### ISSUE THREAD

**Issue by huyangping** [gmag11/EnigmaIOT#7]
Just downloaded the latest repository. I am having serious problems. When compiling the enigmaiot_node example in Arduino 1.8.13 IDE on a debian Linux machine I receive the following compile error:
     Arduino/libraries/EnigmaIOT-master/src/Comms_hal.h:14:21: fatal error: arduino.h: No such file or directory
 #include "arduino.h"
I have installed all of the external libraries listed on the code tab. Any useful assistance would be breatly appreciated.
Glenn G.

**Comment by gmag11** [comment]
It is a case typo. Change `#include "arduino.h"` with `#include "Arduino.h"` in Comms_hal.h. I'll update it soon. Thank you for reporting

**Comment by gmag11** [comment]
This should be solved in latest release https://github.com/gmag11/EnigmaIOT/releases/tag/0.9.3.1

**Comment by huyangping** [comment]
Thank you for correcting the problem so fast. You have my graditude.
Glenn
